### ISSUE TITLE
TdSeq

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV1Q2#1]
La compil de l'eLML ne passe pas le commentaire dans le Java
<paragraph cssClass="java">
  /∗ Commentaire sur
  plusieurs lignes ∗/
à la ligne 938.
Le résultat est bon dans la version en ligne mais incorrect dans le pdf.

**Comment by mcodutti** [comment]
Ton '*' n'est pas l'étoile classique mais une plus grosse.
Je ne sais pas d'où tu la sors !
Avec une étoile normale, c'est OK.

**Comment by cathleruste** [comment]
Merci !
^^ c'est un copier-coller.
Hum hum... c'est public mais non, tu veux pas savoir d'où j'la sors... ;)

**Comment by pbettens** [comment]
Moi je sais 
http://www.demotivateur.fr/article-buzz/on-a-invent-les-pilules-pour-faire-caca-des-paillettes--1427

**Comment by cathleruste** [comment]
^^ En l’occurrence, ce sont des étoiles... 

Plus sérieusement, je n'ai pas le droit de mettre des accents dans les commentaires ??? (j'y regarderai plus tard...)
