### ISSUE TITLE
Séq Rappels: 2.1

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1Q2#14]
Ajouter à la question: et quel nombre de variables avez-vous besoin?

Pour le nom préciser : nom non composé ex Catherine Leruste et non Jean Marc De Mol
ex pour la date : 12/02/2017 et non 12 février 2017

**Comment by cathleruste** [comment]
pour la date, j'acceptais aussi la réponse 2 entiers et 1 chaine mais je retire :)
